
const METRIC_LABEL = {
  HEIGHT: 36,
  VERTICAL_SPACING: 4
};

const DISTANCE_BETWEEN_FILMSTRIPS_AND_TIMELINE = 120;

const METRICS_VISUALIZER_TIMING_SIDE_PADDING = 40;
const METRICS_VISUALIZER_CLS_SIDE_PADDING = 40;

export {
  METRIC_LABEL,
  DISTANCE_BETWEEN_FILMSTRIPS_AND_TIMELINE,
  METRICS_VISUALIZER_TIMING_SIDE_PADDING,
  METRICS_VISUALIZER_CLS_SIDE_PADDING
};
